### ISSUE TITLE
Suggestion: New feature - open all tiddlers in a chosen favourites folder on Story River 

### ISSUE THREAD

**Issue by jonnie45** [kookma/TW-Favorites#3]
Hi, first thank you for a very useful plugin I find it very useful for grouping tiddlers in a large Tiddlywiki in situations where tags are not quite what I want.

Suggestion - a button on each folder that if clicked opens all tiddlers in that folder on the story river.

Example of use: A revision aid - a folder called "essentials" ie the user has decided on a selection of tiddlers that they wish to review before an exam. They might first chose to clear the story river. They then press on the button on the favourites folder called "essentials" and can then revise their sub list of most important points.

Of course this can all be done with a tag called "essentials" but I find the favourites plugin particularly useful for collecting tiddlers of particular interest under categories in a flexible way, it gives a good overview and allows for easy transfer between folders - for instance if an item were to be downgraded from "essentials" to "also very important but not essential".

Great plugin - can't fault it - works exactly as I would wish.

**Comment by kookma** [comment]
Thank you @jonnie45.
For UI simplicity I may add this functionality through mouse <kbd>click+alt</kbd> (customizable)

**Comment by jonnie45** [comment]
Hi Kookma, thanks that's great.

By the way the favourites plugin has turned out to be a useful part of a solution for my continual quest to find a way of grading tiddlers in terms of how useful they are to me - and of course this is often dynamic not static

I now have a Favourites folder called "Musts" - ie the subset of tiddlers I regard of greatest importance.

I have other ranking systems in use - for instance the star ratings plugin and also tags numbered 1,2,3 to signify importance.

The thing I like about the favourites plugin is that once my most important tiddlers are in there I can do the following additional actions..

1. I can order them vertically in the list so that the most important within the group appear near the top, it's so easy to move them up or down when my opinions or needs change.
2. I can read the title without opening the tiddler which means I can view the entire list seeing only the titles as a quick refresher, as soon as I read a title then usually I can remember a reasonable amount of the content and so it serves as a fast mental refresh. 

I have been using the favourites plugin for a long time but it was only recently I realized it might be the solution I was looking for, my knowledge base is currently several thousand tiddlers and so this really helps me manage.

**Comment by kookma** [comment]
added to update 4.7.4
